version: '3.3'

services:

  php:
    build: 
      context: .
      dockerfile: Dockerfile-php
    volumes:
      - ./../sendMessagesPHP/:/app
    ports:
      - 9010:9000

  go:
    build:
      context: .
      dockerfile: Dockerfile-go
    volumes:
      - ./../sendMessagesGo/:/app/
    ports:
      - 8080:8091